//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuplicateDetectorExtension {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DuplicateDetectorExtension {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DuplicateDetectorExtension() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DuplicateDetectorExtension.DuplicateDetectorExtension", typeof(DuplicateDetectorExtension).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding duplicates in a list.
        /// </summary>
        internal static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding duplicates in a list.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates.
        /// </summary>
        internal static string Duplicates {
            get {
                return ResourceManager.GetString("Duplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured while detecting errors.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path of the file containing the text to search the duplicates on.
        /// </summary>
        internal static string InputDescription {
            get {
                return ResourceManager.GetString("InputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; was not found.
        /// </summary>
        internal static string InputFileNotFound {
            get {
                return ResourceManager.GetString("InputFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string LengthSetting {
            get {
                return ResourceManager.GetString("LengthSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the substring to consider when searching for duplicates.
        /// </summary>
        internal static string LengthSettingDescription {
            get {
                return ResourceManager.GetString("LengthSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate detector.
        /// </summary>
        internal static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Input parameter.
        /// </summary>
        internal static string MissingInput {
            get {
                return ResourceManager.GetString("MissingInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If mode is OffsetLength, Offset and Length parameters become mandatory.
        /// </summary>
        internal static string MissingOffsetOrLength {
            get {
                return ResourceManager.GetString("MissingOffsetOrLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string ModeSetting {
            get {
                return ResourceManager.GetString("ModeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mode defines how to search for duplicates. 
        ///“Line” allows you to search for duplicates on the entire line.
        ///“Offset/Length” allows you to search for duplicates in a specific part of each line..
        /// </summary>
        internal static string ModeSettingDescription {
            get {
                return ResourceManager.GetString("ModeSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string ModeSettingLine {
            get {
                return ResourceManager.GetString("ModeSettingLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset / Length.
        /// </summary>
        internal static string ModeSettingOffsetLength {
            get {
                return ResourceManager.GetString("ModeSettingOffsetLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No duplicate found.
        /// </summary>
        internal static string NoDuplicateFound {
            get {
                return ResourceManager.GetString("NoDuplicateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        internal static string OffsetSetting {
            get {
                return ResourceManager.GetString("OffsetSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The zero-based index of the substring to consider in the line when searching duplicates.
        /// </summary>
        internal static string OffsetSettingDescription {
            get {
                return ResourceManager.GetString("OffsetSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result output file.
        /// </summary>
        internal static string OutputFileDescription {
            get {
                return ResourceManager.GetString("OutputFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unduplicate.
        /// </summary>
        internal static string RemoveButtonTitle {
            get {
                return ResourceManager.GetString("RemoveButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the way duplicates are removed :
        ///&quot;KeepFirstOccurence&quot; : Removes duplicates but first
        ///&quot;KeepLastOccurence&quot; : Removes duplicates but last
        ///&quot;RemoveAll&quot; : Removes all duplicates.
        /// </summary>
        internal static string RemoveDuplicatesModeSettingDescription {
            get {
                return ResourceManager.GetString("RemoveDuplicatesModeSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default, output will show found duplicates. If this flag is set, the input text with removed duplicates will be shown instead. .
        /// </summary>
        internal static string RemoveDuplicatesSettingDescription {
            get {
                return ResourceManager.GetString("RemoveDuplicatesSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate detector.
        /// </summary>
        internal static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the way duplicates are removed. RemoveAll removes all lines containing duplicates while KeepFirst or KeepLast keep the first/last occurence.
        /// </summary>
        internal static string UndiplicateSettingDescription {
            get {
                return ResourceManager.GetString("UndiplicateSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep First.
        /// </summary>
        internal static string UnduplicateModeSettingKeepFirst {
            get {
                return ResourceManager.GetString("UnduplicateModeSettingKeepFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Last.
        /// </summary>
        internal static string UnduplicateModeSettingKeepLast {
            get {
                return ResourceManager.GetString("UnduplicateModeSettingKeepLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All.
        /// </summary>
        internal static string UnduplicateModeSettingRemoveAll {
            get {
                return ResourceManager.GetString("UnduplicateModeSettingRemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unduplicate mode.
        /// </summary>
        internal static string UnduplicateSettingTitle {
            get {
                return ResourceManager.GetString("UnduplicateSettingTitle", resourceCulture);
            }
        }
    }
}
