name: publish-nuget
on:
  release: 
    types: [published]

env:
  DOTNET_VERSION: '8.0.x'
  SOLUTION: 'src/DevToysDuplicateDetector.sln'
  
jobs:
  build:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v4
     
     - name: Setup .NET
       uses: actions/setup-dotnet@v4
       with: 
         dotnet-version: ${{ env.DOTNET_VERSION }}

     - name: Clean
       run: dotnet clean -c Release ${{ env.SOLUTION }}

     - name: Restore
       run: dotnet restore ${{ env.SOLUTION }}

     - name: Build Plugin
       run: dotnet build -c Release  ${{ env.SOLUTION }} --no-restore

     - name: Test
       run: dotnet test -c Release ${{ env.SOLUTION }} --no-build

     - name: Build Nuget
       run: dotnet pack -c Release ${{ env.SOLUTION }} -p:Version=${{ github.event.release.tag_name }}
     
     - name: Publish Nuget
       run: dotnet nuget push *.nupkg --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
      
